import type { Metadata } from "next";

import "./globals.css";
import BaseLayout from "@/components/BaseLayout/BaseLayout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <BaseLayout>{children}</BaseLayout>;
}
